# Generated by Django 3.0.8 on 2021-12-24 15:52

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=15)),
                ('avatar', models.TextField()),
                ('wx_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('likes', models.TextField()),
                ('comments', models.TextField()),
                ('content', models.TextField()),
                ('medis', models.TextField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('remarks', models.CharField(max_length=15, verbose_name=backend.models.User)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='backend.User')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('content', models.TextField()),
                ('content_type', models.SmallIntegerField(choices=[(0, 'Picture'), (1, 'Video'), (2, 'Sticker'), (3, 'NameCard')])),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='backend.User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='backend.User')),
            ],
        ),
    ]
